version: "3.7"
services:
  sphinx:
    build:
      context: .
    image: sphinx
    container_name: sphinx-1
    stdin_open: true
    tty: true
    networks:
      hermes-net:
networks:
  hermes-net:
    name: hermes-network
